pull_request_title:
  - '✨ feat: new crowdin updates.'
pull_request_labels:
  - crowdin
  - l10n
commit_message: '✨ feat: new translation \n\n
%original_file_name% translations from Crowdin (%language%)'
append_commit_message: false
files:
  - source: /template/source/**/**
    ignore:
      - /template/%locale_with_underscore%
    translation: /template/%locale_with_underscore%/**/%original_file_name%
