targets:
  - name: Extensions
    sources:
      - /json/source/extensions/*.json
    file: /json/%locale%/extensions/%original_file_name%.json
    format: crowdin-json
  - name: StableDiffusion
    sources:
      - /json/source/StableDiffusion.json
    file: /json/%locale%/StableDiffusion.json
    format: crowdin-json
  - name: ExtensionPage
    sources:
      - /json/source/ExtensionPage.json
    file: /json/%locale%/ExtensionPage.json
    format: crowdin-json
