targets:
  - name: extensions
    sources:
      - /json/source/extensions/*.json
    file: /localizations/%locale%.json
    format: crowdin-json
  - name: StableDiffusion
    sources:
      - /json/source/StableDiffusion.json
      - /json/source/ExtensionPage.json
    file: /localizations/%locale%.json
    format: crowdin-json
files:
  - source: /json/source/extensions/*.json
    translation: /localizations/%locale%.json
  - source: /json/source/StableDiffusion.json
    translation: /localizations/%locale%.json
  - source: /json/source/ExtensionPage.json
    translation: /localizations/%locale%.json
