name: Merge Translates

on:
  workflow_dispatch:

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10.6"
      - name: execute Merger.py
        run: python './json/Merger.py'
