name: Merge Translates

on:
  workflow_dispatch:

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10.6"

      - name: execute Merger.py
        run: python 'json/Merger.py'

      - name: commit files
        run: |
          git config --local user.email "harukaxxxx@makinoworks.com"
          git config --local user.name "harukaxxxx"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Merge zh_TW.json" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
